version: '3'

services:
  postgres:
    image: postgres
    env_file: .env
    container_name: vtuber_clips-postgres
    environment:
      POSTGRES_DB: ${DATABASE_NAME:-nest}
      POSTGRES_USER: ${DATABASE_USERNAME:-nest}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD:-nest}
    ports:
      - '5432:5432'
    volumes:
      - ./apps/postgres:/var/lib/postgresql/data
  nest-app:
    image: node:16
    user: '1000:1000'
    container_name: vtuber_clips-nest-app
    restart: unless-stopped
    env_file: .env
    environment:
      - NODE_OPTIONS=--max_old_space_size=2048
      - NODE_ENV=${APP_ENV:-development}
      - DATABASE_URL=postgresql://${DATABASE_USERNAME:-nest}:${DATABASE_PASSWORD:-nest}@postgres:5432/${DATABASE_NAME:-nest}?connect_timeout=300
    volumes:
      - ./apps/nest-app:/srv/app
      - ./docker/docker-entrypoint.sh:/usr/local/bin/docker-entrypoint.sh
    working_dir: /srv/app
    command: >
      /bin/sh -c "
        if [ ${APP_ENV:-development} == \"production\" ]; then yarn start:prod; else yarn start:dev; fi
      "
    ports:
      - '4000:4000'
    depends_on:
      - postgres
  next-app:
    image: node:16
    user: '1000:1000'
    container_name: vtuber_clips-next-app
    env_file: .env
    ports:
      - '3000:3000'
    environment:
      - NODE_OPTIONS=--max_old_space_size=2048
      - NODE_ENV=${APP_ENV:-development}
    volumes:
      - ./apps/next-app:/srv/app
      - ./docker/docker-entrypoint.sh:/usr/local/bin/docker-entrypoint.sh
    working_dir: /srv/app
    command: >
      /bin/sh -c "if [ ${APP_ENV:-development} == \"production\" ]; then yarn start; else yarn dev; fi"
    