version: '3'

volumes:
  postgres-store:
services:
  postgres:
    image: postgres
    networks:
      - browse_clips_default
    container_name: browse_clips-postgres
    environment:
      POSTGRES_DB: $DATABASE_NAME
      POSTGRES_USER: $DATABASE_USERNAME
      POSTGRES_PASSWORD: $DATABASE_PASSWORD
    ports:
      - $DB_PORT:5432
    volumes:
      - postgres-store:/var/lib/postgresql/data
      - ./backups:/backups
  crawler-app:
    image: mcr.microsoft.com/playwright:latest
    user: '1000:1000'
    container_name: browse_clips-crawler-app
    restart: unless-stopped
    networks:
      - browse_clips_default
    environment:
      - NODE_OPTIONS=--max_old_space_size=2048
      - APP_ENV=$APP_ENV
      - NEST_URL=http://nest-app:4000/
    volumes:
      - ./libs:/srv/wrokspace/libs
      - ./apps/crawler-app:/srv/wrokspace/apps/crawler-app
      - ./docker/docker-entrypoint.sh:/usr/local/bin/docker-entrypoint.sh
      - ./.cache/yarn:/home/pwuser/.yarn/berry/cache
    working_dir: /srv/wrokspace/apps/crawler-app
    command: >
      /bin/sh -c "
        if [ $APP_ENV == \"production\" ]; then yarn start; else yarn dev; fi
      "
    ports:
      - $CRAWLER_PORT:5000
  nest-app:
    image: node:16
    user: '1000:1000'
    container_name: browse_clips-nest-app
    restart: unless-stopped
    networks:
      - browse_clips_default
    environment:
      - NODE_OPTIONS=--max_old_space_size=2048
      - APP_ENV=$APP_ENV
      - NEST_REPL=$NEST_REPL
      - JWT_WECRET=$NEST_JWT_WECRET
      - GOOGLE_API_KEY=$GOOGLE_API_KEY
      - DATABASE_URL=postgresql://$DATABASE_USERNAME:$DATABASE_PASSWORD@postgres:5432/$DATABASE_NAME?connect_timeout=300
    volumes:
      - ./libs:/srv/wrokspace/libs
      - ./apps/nest-app:/srv/wrokspace/apps/nest-app
      - ./docker/docker-entrypoint.sh:/usr/local/bin/docker-entrypoint.sh
      - ./.cache/yarn:/home/node/.yarn/berry/cache
    working_dir: /srv/wrokspace/apps/nest-app
    command: >
      /bin/sh -c "
        yarn prisma migrate dev
        if [ $APP_ENV == \"production\" ]; then yarn start:prod; else yarn start:dev; fi
      "
    ports:
      - $PRISMA_STUDIO_PORT:5555
      - $NEST_PORT:4000
    depends_on:
      - postgres
  next-app:
    image: node:16
    user: '1000:1000'
    container_name: browse_clips-next-app
    networks:
      - browse_clips_default
    ports:
      - $NEXT_PORT:3000
    environment:
      - NODE_OPTIONS=--max_old_space_size=2048
      - APP_ENV=$APP_ENV
      - SERVER_NEST_URL=http://nest-app:4000/
      - PUBLIC_NEST_URL=$PUBLIC_NEST_URL
      - SERVER_NEST_WS_URL=ws://nest-app:5000/
      - PUBLIC_NEST_WS_URL=$PUBLIC_NEST_WS_URL
      - BRAND_NAME=$BRAND_NAME
    volumes:
      - ./libs:/srv/wrokspace/libs
      - ./apps/next-app:/srv/wrokspace/apps/next-app
      - ./docker/docker-entrypoint.sh:/usr/local/bin/docker-entrypoint.sh
      - ./.cache/yarn:/home/node/.yarn/berry/cache
    working_dir: /srv/wrokspace/apps/next-app
    command: >
      /bin/sh -c "
        if [ $APP_ENV == \"production\" ]; then yarn start; else yarn dev; fi
      "
networks:
  browse_clips_default:
    driver: bridge
