#!/usr/bin/env sh

# paths
PROJECT_ROOT="$( cd -- "$(dirname "$0")" >/dev/null 2>&1 ; cd ..; pwd -P )"
YARN_CACHE_DIRECTORY="$(cd -- "$PROJECT_ROOT" >/dev/null 2>&1; cd .cache/yarn; pwd -P)"

cd -- $PROJECT_ROOT/libs

for directory in */; do
  current=$(cd -- $directory; pwd -P)

  /usr/bin/env sh -c "
    cd -- $current
    if [ -f \"package.json\" ]; then
      echo \"================ build lib - $directory ================\"
      yarn
      yarn build
    else
      echo \"$directory is not a nodejs package\"
    fi
  "
done

