#!/usr/bin/env sh

FILEDIR=$(dirname $(realpath "$0"))
PROJECT_ROOT=$(cd $FILEDIR; cd ..; pwd)
DOCKERDIR=$(cd $PROJECT_ROOT; cd docker; pwd)
SCRIPTDIR=$(cd $PROJECT_ROOT; cd scripts; pwd)

# build libs
. "$(cd $SCRIPTDIR; pwd)/build-lib"

cd $DOCKERDIR

build_all=''

while [ $# -gt 0 ] ; do
  case $1 in
    -a | --all) build_all='true' ;;
    *) break ;;
  esac
  shift
done

build_docker () {
  directory_name = $1
  
  if [ -d $directory_name ]; then
    target=$(cd -- $1; pwd -P)
    targetDirname="$(basename $target)"
    image_name="browse_clips-$targetDirname"
    dockerfile_path="$target/Dockerfile"
    /usr/bin/env sh -c "
      cd -- $target
      if [ -f \"Dockerfile\" ]; then
        echo \"================ build docker - $targetDirname ================\"
        docker build -t $image_name:latest -f $dockerfile_path $PROJECT_ROOT
      else
        echo \"Dockerfile is not exist in $targetDirname\"
      fi
    "
  fi
}

if [ $build_all = 'true' ]; then
  for directory_path in */ ; do
    build_docker "$directory_path"
  done
else
  build_docker $1
fi

