#!/usr/bin/env sh

# path
PROJECT_ROOT="$( cd -- "$(dirname "$0")" >/dev/null 2>&1 ; cd ..; pwd -P )"

docker compose exec next-app yarn
docker compose exec nest-app yarn
docker compose exec crawler-app yarn